//! Prepares a writable working copy of the bundled `services/rendezvous-cloudflare` worker so a
//! user can deploy their own personal instance to their own Cloudflare account, orchestrated by
//! the existing PTY infrastructure (`pty.rs`) from the frontend — this module never talks to
//! Cloudflare or the network itself, it only stages files and mints a local secret value. The
//! user's Cloudflare credential is never seen by Alethe: `wrangler login` stores its own OAuth
//! token in the user's local Wrangler config, outside any Alethe-managed directory.

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine;
use rand_core::{OsRng, RngCore};
use std::path::{Path, PathBuf};
use tauri::Manager;

const WORKER_RESOURCE_DIR: &str = "rendezvous-cloudflare";
/// Entries never copied into the writable working copy: `node_modules` because it is large and
/// regenerated by `npm install` anyway, and dotfiles/build output that don't matter for a deploy.
const SKIP_ENTRIES: [&str; 4] = ["node_modules", "dist", ".wrangler", "test"];

fn copy_dir_recursive(source: &Path, destination: &Path) -> Result<(), String> {
    std::fs::create_dir_all(destination).map_err(|error| error.to_string())?;
    for entry in std::fs::read_dir(source).map_err(|error| error.to_string())? {
        let entry = entry.map_err(|error| error.to_string())?;
        let name = entry.file_name();
        let Some(name_str) = name.to_str() else { continue };
        if SKIP_ENTRIES.contains(&name_str) {
            continue;
        }
        let from = entry.path();
        let to = destination.join(&name);
        let file_type = entry.file_type().map_err(|error| error.to_string())?;
        if file_type.is_dir() {
            copy_dir_recursive(&from, &to)?;
        } else {
            std::fs::copy(&from, &to).map_err(|error| error.to_string())?;
        }
    }
    Ok(())
}

/// Resolves the bundled worker source. In a packaged build this is the Tauri resource directory;
/// in `tauri dev`, the resource dir mirrors the same relative layout from the repository root, so
/// both paths are tried and the first one that actually exists wins.
fn locate_bundled_source(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    if let Ok(resource_path) = app
        .path()
        .resolve(WORKER_RESOURCE_DIR, tauri::path::BaseDirectory::Resource)
    {
        if resource_path.is_dir() {
            return Ok(resource_path);
        }
    }
    // Dev fallback: `tauri dev` doesn't always stage `bundle.resources` into a resource dir, so
    // fall back to the monorepo path relative to this crate (`src-tauri/../services/...`).
    let dev_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../services/rendezvous-cloudflare");
    if dev_path.is_dir() {
        return Ok(dev_path);
    }
    Err("cloudflare_worker_resource_missing".to_string())
}

/// Copies the bundled worker source into a writable per-install directory and returns its path,
/// ready to be used as a PTY `cwd` for `npm install` / `wrangler login` / `wrangler deploy`. Safe
/// to call repeatedly — it always re-syncs source files (never touching `node_modules`), so a
/// newer app version's worker source is picked up on the next deploy attempt.
#[tauri::command]
pub fn cloudflare_deploy_workdir(app: tauri::AppHandle) -> Result<String, String> {
    let data_root = crate::profiles::resolve_tauri_data_root(&app)?;
    let source = locate_bundled_source(&app)?;
    let destination = data_root.join("cloudflare-deploy").join(WORKER_RESOURCE_DIR);
    copy_dir_recursive(&source, &destination)?;
    Ok(destination.to_string_lossy().to_string())
}

/// Mints a random value for the deployed worker's `ABUSE_HASH_KEY` secret (see
/// `services/rendezvous-cloudflare/README.md`) — generated locally, never sent anywhere except
/// piped straight into `wrangler secret put` by the caller, and never persisted by Alethe itself.
#[tauri::command]
pub fn cloudflare_generate_secret() -> String {
    let mut bytes = [0_u8; 32];
    OsRng.fill_bytes(&mut bytes);
    URL_SAFE_NO_PAD.encode(bytes)
}

#[derive(Clone, Debug, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CloudflareProbeState {
    /// Whether `wrangler` is already installed in this device's deploy working copy
    /// (`node_modules/wrangler` present — i.e. `npm install` has completed at least once).
    pub installed: bool,
    /// Whether this device is currently authenticated with a Cloudflare account, per
    /// `wrangler whoami`. Always `false` when `installed` is `false` — this is deliberately never
    /// probed by installing anything (see `probe_wrangler_login`'s own doc comment).
    pub logged_in: bool,
}

/// Read-only status for the sidebar's 3-state Cloudflare card: not installed, installed-but-not-
/// logged-in, or ready. Never installs, deploys, or writes anything — the two real actions
/// (`cloudflare_deploy_workdir` + the frontend's PTY-driven `npm install`/`wrangler login`/
/// `wrangler deploy` chain) stay exactly as they were.
#[tauri::command]
pub async fn cloudflare_probe_state(app: tauri::AppHandle) -> CloudflareProbeState {
    let Ok(data_root) = crate::profiles::resolve_tauri_data_root(&app) else {
        return CloudflareProbeState { installed: false, logged_in: false };
    };
    let workdir = data_root.join("cloudflare-deploy").join(WORKER_RESOURCE_DIR);
    let installed = workdir.join("node_modules").join("wrangler").is_dir();
    if !installed {
        return CloudflareProbeState { installed: false, logged_in: false };
    }
    let logged_in = probe_wrangler_login(&workdir).await;
    CloudflareProbeState { installed: true, logged_in }
}

/// Runs `npx wrangler whoami` in `workdir` to check login state — safe to call only once
/// `wrangler` is confirmed already installed there (`node_modules/wrangler` exists), so `npx`
/// always resolves the already-present local binary and never silently downloads anything over
/// the network just to answer a status question. Fails closed (`false`) on any error, non-zero
/// exit, or timeout, rather than ever falsely reporting "logged in".
async fn probe_wrangler_login(workdir: &Path) -> bool {
    let npx = if cfg!(windows) { "npx.cmd" } else { "npx" };
    let mut command = tokio::process::Command::new(npx);
    command
        .arg("wrangler")
        .arg("whoami")
        .current_dir(workdir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());
    #[cfg(windows)]
    {
        // CREATE_NO_WINDOW — this is a background status check, never a console flash.
        command.creation_flags(0x0800_0000);
    }
    let Ok(Ok(output)) =
        tokio::time::timeout(std::time::Duration::from_secs(10), command.output()).await
    else {
        return false;
    };
    let combined =
        format!("{}{}", String::from_utf8_lossy(&output.stdout), String::from_utf8_lossy(&output.stderr))
            .to_lowercase();
    combined.contains("you are logged in") || combined.contains("you're logged in")
}
